name: md to pdf builder

on:
  push:
    tags:
      - 'v*.*' 

jobs:
  runs-on: ubuntu-20.04
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pandoc
      run: sudo apt install pandoc

    - name: Convert
      run: pandoc --from=gfm --to=pdf -o README.pdf README.md
    
    - name: Release
      uses: softprops/action-gh-release@v1
        with:
          files: |
            README.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}