name: md to pdf builder

on:
  push:
    branches:
      - 'master'

jobs:
  runs-on: ubuntu-20.04
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install markdown-pdf
      run: npm install -g markdown-pdf

    - name: Convert
      run: markdown-pdf README.md