name: md to pdf builder

on:
  push:
    tags:
      - 'v*.*' 

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: sudo apt update
      - name: Install pandoc
        run: sudo apt-get install pandoc
      - run: sudo apt-get install texlive texlive-latex-extra
      - run: sudo apt install texlive-latex-base pandoc texlive-fonts-recommended

      - name: Convert
        run: pandoc -s -o README.md README.pdf 
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            README.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}