name: md to pdf builder

on:
  push:
    tags:
      - 'v*.*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: sudo apt update

      - name: Install pandoc
        run: sudo apt-get install pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra

      - name: Convert
        run : pandoc README.md -s -o output.html 
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            output.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}