name: md to pdf builder

on:
  push:
    tags:
      - 'v*.*' 

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pandoc
        run: sudo apt install pandoc

      - name: Convert
        run: pandoc README.md -o README.pdf 
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            README.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}