name: md to pdf builder

on:
  push:
    tags:
      - 'v*.*' 

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: sudo apt update

      - name: Install pandoc
        run: sudo apt-get install pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra

      - name: Convert
        #run : pandoc --standalone --embed-resource -c github-markdown.css -f gfm -t html README.md -o output.html 
        run: pandoc --standalone -c images/github-markdown.css -f gfm -t html README.md -o output.html
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            output.html
            images
            images/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}